name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Nécessaire pour lire le contenu du dépôt
      pages: write   # Nécessaire pour déployer sur GitHub Pages
      id-token: write # Nécessaire pour l'authentification OIDC
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - run: bundle install
      - run: bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
      - uses: actions/deploy-pages@v4
